apps/blog/urls.py
from django.urls import path
from .views.blog_views import  post_list, post_detail, create_post, update_post, delete_post

app_name = "blog"

urlpatterns = [
    path("tag/<slug:tag_slug>/", post_list, name="post_list_by_tag"), 
    path("create_post/", create_post, name="create_post"),
    path("post_list/", post_list, name="post_list"),
    path("<slug:post>/", post_detail, name="post_detail"),
    path("update_post/<slug:post>/", update_post, name="update_post"), 
    path("delete_post/<slug:post>/", delete_post, name="delete_post")
]

apps/custom_auth/urls.py
from django.urls import path
from .views import login_view, signup_done_view, signup_view, logout_view

app_name = 'custom_auth'

urlpatterns = [
    path(
        "login/", login_view, name="login"
    ),
    
    path(
        "signup-done/", signup_done_view, name="signup_done"
    ),
    
    path(
        "signup/", signup_view, name="signup"
    ),
    
    path(
        "logout/", 
        logout_view, 
        name="logout"
    )
]

blogproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.core.urls", namespace="core")),
    path("custom_auth/", include("apps.custom_auth.urls", namespace="custom_auth")),
    path("blog/", include("apps.blog.urls", namespace="blog"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models/comment_model.py
from django.db import models 
from django.contrib.auth import get_user_model

from ..models.post_model import Post

class Comment(models.Model): 
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta: 
        ordering = ["created"]
        indexes = [
            models.Index(fields=["created"])
        ]
        
        
    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

apps/blog/models/post_model.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.text import slugify

from taggit.managers import TaggableManager

User = get_user_model()

class PostStatusManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED) 
    
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        
    # Object managers 
    objects = models.Manager()    # por defecto
    published = PostStatusManager()    
    
    tags = TaggableManager()
    # Atributos
    title_post = models.CharField(max_length=150)
    slug_title = models.SlugField(unique=True, blank=True, null=True)
    image_post = models.ImageField(upload_to="image-post/")
    publish = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)
    
    """
        Si no se coloca 'related_name', por defecto la relación inversa entre los modelos será con 'nombremodelo_set'
    """
    
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="blog_posts"
    )
    
    body = models.TextField()
    status = models.CharField(
        max_length=2, 
        choices=Status,
        default=Status.DRAFT
    )
    
    class Meta:
        indexes = [
            models.Index(fields=['author', 'title_post'])
        ]
        
        ordering = ["id"]
      
    def save(self, *args, **kwargs):
        if not self.slug_title:
            base_slug = slugify(self.title_post)
            slug_title = base_slug
            n = 1
            while Post.objects.filter(slug_title=slug_title).exists():
                slug_title = f"{base_slug}-{n}"
                n += 1
            self.slug_title = slug_title
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.slug_title])
    
    def __str__(self):
        return self.title_post
    

apps/blog/forms/comment_form.py
from ..models.comment_model import Comment
from django import forms

class CommentForm(forms.ModelForm): 
    class Meta: 
        model = Comment 
        fields = ["body"]
        
        

apps/blog/forms/post_form.py
from django import forms
from ..models.post_model import Post  
from apps.blog.validators.title import validar_title
from taggit.forms import TagWidget

class PostForm(forms.ModelForm):
    title_post = forms.CharField(
        required=True, 
        max_length=150,
        validators=[validar_title],
        widget=forms.TextInput(
            attrs={
                "placeholder": "Título del post",
                "minlength": "10",
                "maxlength": "150",
            }
        )
    )
    
    image_post = forms.ImageField(
        required=True,
    )
    
    body = forms.CharField(
        required=True, 
        widget=forms.Textarea(
            attrs={
                "placeholder": "Body",
            }
        )
    )

    class Meta:
        model = Post
        fields = ["tags", "title_post", "image_post", "author", "body", "status"]
        widgets = {
            "tags": TagWidget(
                attrs={
                    "placeholder": "Tags separados por coma",
                }
            )
        }
    

apps/blog/views/blog_views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from apps.blog.models.post_model import Post
from ..forms.post_form import PostForm
from apps.blog.models.comment_model import Comment 
from ..forms.comment_form import CommentForm

from apps.core.utils.markdown_format import render_markdown
from taggit.models import Tag

@login_required
def post_list(request, tag_slug=None): 
    post_list = Post.published.all()
    
    tag = None 
    if tag_slug: 
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
        
    
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page')
    
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
        
    return render(
        request,
        'blog/list.html',
        {'posts': posts, "tag": tag}
    )

@login_required
def post_detail(request, post):
    post = get_object_or_404(
        Post,
        slug_title=post,
        status=Post.Status.PUBLISHED
    )
    
    # Atributo temporal en tiempo de ejecución
    post.body_html = render_markdown(post.body)
    
    comments = post.comments.filter(active=True).order_by("-created")
    new_comment = None 
    
    if request.method == "POST": 
        form = CommentForm(data=request.POST)
        
        if form.is_valid(): 
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.name = request.user.get_full_name() 
            new_comment.email = request.user.email 
            new_comment.save()
            
            return redirect('blog:post_detail', post=post.slug_title)
    else: 
        form = CommentForm()
            
        
    return render(
        request,
        'blog/detail.html',
        {
            'post': post, 
            "comments": comments, 
            "form": form
        }
    )

@login_required
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
                
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            form.save_m2m() 
                     
            return redirect("blog:post_list") 
    else:
        form = PostForm()
    
    return render(request, "blog/create.html", {"form": form})

@login_required
def update_post(request, post): 
    post = get_object_or_404(
        Post, 
        slug_title=post,
        # Solo el autor original del post pueda editar o eliminar su contenido.
        author=request.user    
    )

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        
        if form.is_valid():
            updated_post = form.save(commit=False)
            updated_post.save()
            form.save_m2m()
            
            return redirect("blog:post_list")
    else: 
        form = PostForm(instance=post) 
        
    return render(request, "blog/update.html", {"form": form, "post": post})
    
@login_required
def delete_post(request, post):
    post = get_object_or_404(
        Post, 
        slug_title=post,
        # Solo el autor original del post pueda editar o eliminar su contenido.
        author=request.user
    )
    
    if request.method == "POST":
        post.delete()
        
        return redirect("blog:post_list")
    
    return render(request, "blog/delete.html", {"post": post})

apps/blog/templates/blog/create.html
{% extends "base/base.html" %}
{% load static %}

{% block pag_descrip %} Create post {% endblock pag_descrip %}
{% block title_pag %} Create Post 🖋️ | Blog Gate 💻 {% endblock title_pag %}
{% block favicon %} 
    https://th.bing.com/th/id/R.364af3c5c0ded42bd3a26d460b30b7f9?rik=zAx7zasTQyLRRw&pid=ImgRaw&r=0
{% endblock favicon %}
{% block css_styles %}
    <style>
        select, ::picker(select) { 
            appearance: base-select;
        }

        option{ 
            padding: 6px 10px;

            &:checked {
                background-color: #09f;
            }
        }

        textarea {
            resize: none;
            overflow: hidden;
            width: 450px;
        }

        input[type="text"], textarea, select, input[type="file"] { 
            background-color: #e5e7eb;
            padding: 6px 10px;
            border: 0;
            outline: 0;
        }
    </style>
{% endblock css_styles %}

{% block content %}
    <header class="bg-black text-white px-4 py-6 flex justify-center items-center container-sticky ">
        <h2 class="tracking-widest font-bold font-ubuntu text-xl text-center">Crear post</h2>
    </header>

    <form method="POST" class="py-6" enctype="multipart/form-data">
        {% csrf_token %}

        {% if form.non_field_errors %}
            <ul class="text-red-600 text-sm">
                {% for error in form.non_field_errors %}
                    <li class="text-center">{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <div class="flexbox1 gap-4">
            {% for field in form %}
                <div class="flex items-center gap-4">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% if field.errors %}
                        <ul class="text-red-600 text-sm">
                            {% for error in field.errors %}
                                <li class="text-center">{{ error }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    
                    {{ field }}
                </div>
            {% endfor %}
        </div>

        <div class="flex justify-center mt-4">
            <button type="submit" class="btn-primary">Crear</button>
        </div>
    </form>
    
    {% block js_files %}
        <script src="{% static "js/utilities/textarea.js" %}"></script>
    {% endblock js_files %}
{% endblock content %}

apps/blog/templates/blog/delete.html
{% extends "base/base.html" %}
{% load static %}

{% block pag_descrip %} Borrar post {% endblock pag_descrip %}
{% block title_pag %} Borrar post #{{ post.id }} | BlogGate 💻 {% endblock title_pag %}
{% block favicon %}
    https://cdn-icons-png.flaticon.com/512/200/200389.png
{% endblock favicon %}

{% block content %}
    <header class="bg-black text-white px-4 py-6 flex justify-center items-center container-sticky">
        <h2 class="tracking-widest font-bold font-ubuntu text-xl text-center">Eliminar post #{{ post.id }}</h2>
    </header>

    <form method="POST" id="deleteForm" class="flex justify-center mt-6">
        {% csrf_token %}

        <button class="btn-danger">Eliminar post</button>
    </form>

    <script>
        document.addEventListener("submit", (e) => {
            if (e.target.matches("#deleteForm")) {
                e.preventDefault();

                Swal.fire({
                    title: '¿Estás seguro?',
                    text: "¡No podrás deshacer esta acción!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#3085d6',
                    confirmButtonText: 'Sí, eliminar',
                    cancelButtonText: 'Cancelar'

                }).then((result) => {
                    if (result.isConfirmed) {
                        document.getElementById("deleteForm").submit();
                    }
                });                
            }
        })
    </script>
{% endblock content %}

apps/blog/templates/blog/detail.html
{% extends "base/base.html" %}
{% load static %}

{% block pag_descrip %} Detalle del post #{{ post.id }} {% endblock pag_descrip %}
{% block title_pag %} Post #{{ post.id }} | BlogGate 💻 {% endblock title_pag %}
{% block favicon %}
    https://cdn-icons-png.flaticon.com/512/15356/15356814.png
{% endblock favicon %}
{% block css_styles %}
    <style>
        form #id_body {
            resize: none;
            field-sizing: content;
            overflow: hidden;
            width: 450px;
            height: 35px;
            outline-0;
            border: 2px solid white;
        }
    </style>
{% endblock css_styles %}

{% block content %}
    <header class="bg-black text-white px-4 py-6 flex justify-center items-center container-sticky ">
        <h2 class="tracking-widest font-bold font-ubuntu text-xl text-center">Detalle del Post #{{ post.id }}</h2>
    </header>

    <main>
        <section class="py-5 px-7 flex flex-col items-center gap-6">
            <h2 class="tracking-widest font-semibold text-xl">{{ post.title_post }}</h2>

            <p>Autor: <span class="font-semibold">{{ post.author.first_name }} {{ post.author.last_name }}</span></p>

            <p>Fecha de creación: <span class="font-semibold">{{ post.publish }}</span></p>

            <p>Fecha de modificación: <span class="font-semibold">{{ post.edited }}</span></p>
            
            <img src="{{ post.image_post.url }}" class="w-102 h-52 border-2 border-black rounded-2xl object-cover">

            <div class="w-[700px] flex flex-col gap-6 max-lg:w-3/4_w">{{ post.body_html|safe }}</div>

            <a class="btn-primary" href="{% url "blog:post_list" %}">Regresar</a>
        </section>

        <section class="p-4 bg-black/85 text-white">
            {% with comments.count as total_comments %}
                <h2 class="text-xl font-semibold">Comentarios ({{ total_comments }})</h2>
            {% endwith %}

            <div class="flex flex-col gap-4 mt-4">
                {% for comment in comments %}
                    <div class="bg-white shadow-md rounded-xl p-4 border border-gray-200">
                        <div class="flex justify-between items-center mb-2">
                            <h3 class="text-lg font-semibold text-gray-800">{{ comment.name }}</h3>
                            <p class="text-sm text-gray-500">{{ comment.created }}</p>
                        </div>
                        <p class="text-gray-700">{{ comment.body }}</p>
                    </div>
                {% empty %}
                    <p class="text-gray-500 text-sm">No hay comentarios. ¡Sé el primero en comentar!</p>
                {% endfor %}
            </div>


            <hr class="mt-4 mb-4"> 

            <div class="flex flex-col gap-4">
                <h2>Añadir un comentario</h2>

                <form method="post" class="flex flex-col gap-4">
                    {% csrf_token %}
                    
                    {% for field in form %}
                        <div class="flex gap-6 items-center">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}

                    <div class="flex justify-start">
                        <button type="submit" class="btn-secondary ">Agregar comentario</button>
                    </div>
                </form>
            </div>
        </section>
    </main>

    {% block js_files %}
        <script src="{% static "js/utilities/textarea.js" %}"></script>
    {% endblock js_files %}
{% endblock content %}

apps/blog/templates/blog/list.html
{% extends "base/base.html" %}
{% load blog_tags %}

{% block pag_descrip %} Lista de blogs {% endblock pag_descrip %}
{% block title_pag %} Lista de blogs | BlogGate 💻 {% endblock title_pag %}
{% block favicon %}
    https://static.vecteezy.com/system/resources/previews/022/791/223/original/blog-site-blogger-png.png
{% endblock favicon %}

{% block content %}
    <body>
        <header class="bg-black text-white px-4 py-6 flex justify-between items-center container-sticky">
            <h2 class="text-xl text-center font-semibold tracking-widest font-playpen-sans">Lista de publicaciones</h2>
            <form action="{% url 'custom_auth:logout' %}" method="post">
                {% csrf_token %}
                <button class="cursor-pointer font-semibold tracking-widest transition hover:text-red-500">Cerrar sesión</button>
            </form>
        </header>

        <main class="py-6 px-5">
            <section class="px-5 py-7 flex flex-col gap-5">
                <h2 class="font-ubuntu text-2xl text-center">Total de posts: {% total_posts %}</h2>

                <a class="btn-primary mx-auto my-0" href="{% url "blog:create_post" %}">Crear post</a>
                
                {% if tag %}
                    <h2 class="text-2xl">Post con la etiqueta <span class="font-semibold font-raleway">"{{ tag.name }}"</span></h2>
                {% endif %}
                
                {% for post in posts %}
                    <div class="flex flex-col gap-5">
                        <div>
                            <h3>Título del post: <span class="font-semibold"><a href="{{ post.get_absolute_url }}" class="transition hover:text-blue-700">{{ post.title_post }}</a></span></h3>
                            <p>Nombre del autor: <span class="font-semibold">{{ post.author.first_name }} {{ post.author.last_name }}</span></p>
                            <p>Etiquetas: 
                                
                                {% for tag in post.tags.all %}
                                    <a href="{% url "blog:post_list_by_tag" tag.slug %}" class="font-semibold text-blue-600 transition hover:text-blue-800">
                                    {{ tag.name }}
                                    </a>{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </p>
                            <p>Fecha de publicación: <span class="font-semibold">{{ post.publish }}</span></p>
                            <p>Fecha de modificación: <span class="font-semibold">{{ post.edited }}</span></p>
                        </div>

                        <div class="flex gap-4">
                            <a href="{% url "blog:update_post" post.slug_title  %}" class="btn-secondary">Editar</a>
                            <a href="{% url "blog:delete_post" post.slug_title %}" class="btn-danger">Eliminar</a>
                        </div>

                        <hr>
                    </div>
                {% endfor %}
            </section>

            <section>
                {% include "fragments/pagination.html" with page=posts %}
            </section>
        </main>
    </body>
{% endblock content %}

apps/blog/templates/blog/update.html
{% extends "base/base.html" %}
{% load static %}

{% block pag_descrip %} Update post {% endblock pag_descrip %}
{% block title_pag %} Update post #{{ post.id }} | BlogGate 💻 {% endblock title_pag %}
{% block favicon %}
    https://cdn-icons-png.flaticon.com/512/200/200389.png
{% endblock favicon %}
{% block css_styles %}
    <style>
        select, ::picker(select) { 
            appearance: base-select;
        }

        option{ 
            padding: 6px 10px;

            &:checked {
                background-color: #09f;
            }
        }

        textarea {
            resize: none;
            overflow: hidden;
            width: 450px;
        }

        input[type="text"], textarea, select, input[type="file"] { 
            background-color: #e5e7eb;
            padding: 6px 10px;
            border: 0;
            outline: 0;
        }
        
        div br {
            display: none;
        }
    </style>
{% endblock css_styles %}

{% block content %}
    <header class="bg-black text-white px-4 py-6 flex justify-center items-center container-sticky">
        <h2 class="tracking-widest font-bold font-ubuntu text-xl text-center">Actualizar Post</h2>
    </header>

    <section class="px-4 py-6 flexbox1 gap-3">
        <h2 class="text-xl font-ubuntu font-semibold tracking-widest">Post # {{ post.id }}: {{ post.title_post }}</h2>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {% if form.non_field_errors %}
                <ul class="text-red-600 text-sm">
                    {% for error in form.non_field_errors %}
                        <li class="text-center">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <div class="flexbox1 gap-4">
                {% for field in form %}
                    <div class="flex items-center justify-center gap-4">
                        {% if field.errors %}
                            <ul class="text-red-600 text-sm">
                                {% for error in field.errors %}
                                    <li class="text-center">{{ error }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                        <div class="flex gap-4 justify-center items-center">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="flex justify-center mt-4">
                <button type="submit" class="btn-primary">Actualizar</button>
            </div>
        </form>
    </section>

    {% block js_files %}
        <script src="{% static "js/utilities/textarea.js" %}"></script>
    {% endblock js_files %}
{% endblock content %}