apps/custom_auth/urls.py
from django.urls import path
from .views import login_view, signup_done_view, signup_view, logout_view

app_name = 'custom_auth'

urlpatterns = [
    path(
        "login/", login_view, name="login"
    ),
    
    path(
        "signup-done/", signup_done_view, name="signup_done"
    ),
    
    path(
        "signup/", signup_view, name="signup"
    ),
    
    path(
        "logout/", 
        logout_view, 
        name="logout"
    )
]

blogproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.core.urls", namespace="core")),
    path("custom_auth/", include("apps.custom_auth.urls", namespace="custom_auth")),
    path("blog/", include("apps.blog.urls", namespace="blog"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/custom_auth/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from apps.custom_auth.validators.email import validar_email
from apps.custom_auth.validators.name import validar_nombre
from apps.custom_auth.validators.username import validar_username
from apps.custom_auth.validators.password import validar_password
from django.contrib.auth.password_validation import validate_password

class CustomUserManager(BaseUserManager): 
    def create_user(self, email, password=None, **extra_fields): 
        if not email: 
            raise ValueError("El correo es obligatorio")
        
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        
        if password:
            validar_password(password)                  # Regex
            validate_password(password, user=user)      # Django nativo

        
        user.set_password(password)
        user.save(using=self._db)
        return user
        
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("El superusuario debe tener is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("El superusuario debe tener is_superuser=True.")

        return self.create_user(email, password, **extra_fields)

    
class CustomUser(AbstractBaseUser, PermissionsMixin): 
    first_name = models.CharField(max_length=30, validators=[validar_nombre])
    last_name = models.CharField(max_length=30, validators=[validar_nombre])
    username = models.CharField(max_length=20, validators=[validar_username], unique=True)
    email = models.EmailField(max_length=254, validators=[validar_email], unique=True)
    password = models.CharField(max_length=128)      # Lo guarda 
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    
    objects = CustomUserManager()
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name", "username"]
    
    def __str__(self):
        return self.email
    
    def get_full_name(self): 
        return f"{self.first_name} {self.last_name}"
    
    def get_short_name(self): 
        return self.first_name
    
    class Meta:
        verbose_name = "usuario"
        verbose_name_plural = "usuarios"

apps/custom_auth/forms/login.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model, authenticate

from apps.custom_auth.validators.email import validar_email

User = get_user_model()

class LoginForm(forms.Form): 
    email = forms.EmailField(
        validators=[validar_email],
        max_length=254,
        required=True,
        widget=forms.EmailInput(
            attrs={
                "placeholder": "email",
                "minlength": "6",
                "maxlength": "254", 
                "class": "bg-gray-200 px-3 py-2 outline-0 w-80 max-md:w-[60vw]"
            }
        )
    )
    
    password = forms.CharField(
        required=True,
        max_length=128,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "password",
                "minlength": "8",
                "maxlength": "128",
                "class": "bg-gray-200 px-3 py-2 outline-0 w-80 max-md:w-[60vw]"
            }
        )
    )
    
    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        password = cleaned_data.get("password")
        
        if email and password:
            user = authenticate(email=email, password=password)
        
            if user is None: 
                raise ValidationError("Este correo no está registrado o las credenciales no coinciden.")
            
            if not user.is_active:
                raise ValidationError("El usuario está inactivo")
            
            # guarda el usuario autenticado en la instancia del formulario   
            self.user = user    
        
        return cleaned_data
    
    def clean_email(self):
        email = self.cleaned_data.get("email", "")
        email =  email.lower().strip()

        return email
    
    def clean_password(self): 
        password = self.cleaned_data.get("password", "")
        password = password.strip()
        
        return password
    
    def get_user(self): 
        return getattr(self, "user", None)

apps/custom_auth/forms/signup.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from apps.custom_auth.validators.password import validar_password
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password

User = get_user_model()

class SignUpForm(UserCreationForm):    
    password1 = forms.CharField(
        max_length=128,
        required=True,
        validators=[validar_password],
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "password",
                "minlength": "8",
                "maxlength": "128",
                "class": "bg-gray-200 px-3 py-2 outline-0 w-72 max-md:w-[70vw]"
            }
        )
    )
        
    password2 = forms.CharField(
        max_length=128,
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "confirm password",
                "minlength": "8",
                "maxlength": "128",
                "class": "bg-gray-200 px-3 py-2 outline-0 w-72 max-md:w-[70vw]"
            }
        )
    )
    
    first_name = forms.CharField(
        required=True, 
        widget=forms.TextInput(
            attrs={
                "placeholder": "first_name",
                "minlength": "3",
                "maxlength": "30",
                "class": "bg-gray-200 px-3 py-2 outline-0 w-72 max-md:w-[70vw]"
            }
        )
    )
    
    last_name = forms.CharField(
        required=True, 
        widget=forms.TextInput(
            attrs={
                "placeholder": "last_name",
                "minlength": "3",
                "maxlength": "30",
                "class": "bg-gray-200 px-3 py-2 outline-0 w-72 max-md:w-[70vw]"
            }
        )
    )
    
    username = forms.CharField(
        required=True, 
        widget=forms.TextInput(
            attrs={
                "placeholder": "username",
                "minlength": "6",
                "maxlength": "20",
                "class": "bg-gray-200 px-3 py-2 outline-0 w-72 max-md:w-[70vw]"
            }
        )
    )
    
    email = forms.EmailField(
        required=True, 
        widget=forms.EmailInput(
            attrs={
                "placeholder": "email",
                "minlength": "6",
                "maxlength": "254",
                "class": "bg-gray-200 px-3 py-2 outline-0 w-72 max-md:w-[70vw]"
            }
        )
    )
    
    class Meta: 
        model = User
        fields = ["first_name", "last_name", "username", "email"]
        
    def clean(self): 
        cleaned_data = super().clean()

        for campo in self.Meta.fields:
            valor = cleaned_data.get(campo)
            
            if isinstance(valor, str):
                cleaned_data[campo] = valor.strip()
            
        return cleaned_data
    
    def clean_username(self): 
        username = self.cleaned_data["username"].lower().strip()
        
        if User.objects.filter(username=username).exists():
            raise ValidationError("El username ya se encuentra registrado")
    
        return username
    
    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if password1:
            validar_password(password1)   # Tu regex
            validate_password(password1)  # Validación Django
        return password1
    
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise ValidationError("Las contraseñas no coinciden")

        return password2

    def clean_email(self):
        email = self.cleaned_data["email"].lower().strip()
        
        if User.objects.filter(email=email).exists():
            raise ValidationError("El correo ya se encuentra registrado")
    
        return email
    
    

apps/custom_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required
  
from .forms.login import LoginForm
from .forms.signup import SignUpForm

def login_view(request): 
    if request.user.is_authenticated:
        return redirect("blog:post_list")
    
    if request.method == "POST": 
        form = LoginForm(request.POST) 
        
        if form.is_valid(): 
            login(request, form.get_user())
            request.session["last_login"] = now().isoformat()
            
            return redirect("blog:post_list")
                     
    else:
        form = LoginForm()
        
    return render(
        request, 
        "custom_auth/login.html", 
        {"form": form}
    )

def signup_done_view(request):
    if request.user.is_authenticated: 
        return redirect("blog:post_list")
    
    return render(request, "custom_auth/signup_done.html")

def signup_view(request): 
    if request.user.is_authenticated: 
        return redirect("blog:post_list")
    
    if request.method == "POST":
        form = SignUpForm(request.POST)
        
        if form.is_valid(): 
            form.save()
            return redirect("custom_auth:signup_done")
    else: 
        form = SignUpForm()
    
    return render(
        request, 
        "custom_auth/signup.html",
        {"form": form}
    )
    
@login_required 
def logout_view(request): 
    logout(request)
    return redirect("core:home")

apps/custom_auth/templates/custom_auth/login.html
{% extends "base/base_auth.html" %}
{% load static %}

{% block pag_descrip %} Login {% endblock pag_descrip %}
{% block title_pag %} Login | BlogGate 💻 {% endblock title_pag %}
{% block favicon %}
    https://th.bing.com/th/id/R.a9b7e00dfdfb1e4453332194aaf55419?rik=fzfT8puCgr7EFg&pid=ImgRaw&r=0
{% endblock favicon %}

{% block title_auth %} Login {% endblock title_auth %}
{% block inputs %}
    {% if form.non_field_errors %}
        <ul class="text-red-600 text-sm">
            {% for error in form.non_field_errors %}
                <li class="text-center">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <div class="flexbox1 gap-5">
        {% for field in form %}
            <div class="flex flex-col items-start gap-1">
                {% if field.errors %}
                    <ul class="text-red-600 text-sm">
                        {% for error in field.errors %}
                            <li class="text-center">{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {{ field }}
            </div>
        {% endfor %}
    </div>
{% endblock inputs %}
{% block btn_auth %}
    <button type="submit" class="mx-auto btn-primary w-80 max-md:w-[60vw]">Iniciar sesión</button>
{% endblock btn_auth %}

{% block text_alt %}
    ¿No tienes una cuenta? <a href="{% url "custom_auth:signup"  %}" class="text-blue-800 font-semibold tracking-wider transition-colors  hover:text-blue-900">Registrarse</a>
{% endblock text_alt %}

apps/custom_auth/templates/custom_auth/session_expired.html
{% extends "base/base.html" %}
{% load static %}

{% block pag_descrip %} Session xpired {% endblock pag_descrip %}
{% block title_pag %} Session expired | BlogGate 💻 {% endblock title_pag %}
{% block favicon %}
    https://cdn-icons-png.freepik.com/256/6227/6227474.png
{% endblock favicon %}

{% block content %}
    <body class="background-auth min-h-screen flex justify-center items-center">
        <section class="bg-white rounded-lg w-115 max-md:w-3/4_w h-auto px-5 py-6 flex flex-col justify-center items-center gap-5">
            <h2>Sesión expirada</h2>
            <p>Tu sesión ha caducado, por favor vuelve a iniciar sesión</p>
            <a class="btn-primary" href="{% static "custom_auth:login" %}">Login</a>
        </section>
    </body>
{% endblock content %}

apps/custom_auth/templates/custom_auth/signup.html
{% extends "base/base_auth.html" %}
{% load static %}

{% block pag_descrip %} Signup {% endblock pag_descrip %}
{% block title_pag %} Signup | BlogGate 💻 {% endblock title_pag %}
{% block favicon %}
    https://cdn-icons-png.flaticon.com/512/9194/9194815.png
{% endblock favicon %}

{% block css_styles %}
    <style>
        section { 
            width: 680px;
        }
    </style>
{% endblock css_styles %}

{% block title_auth %} Signup {% endblock title_auth %}
{% block inputs %}
    {% if form.non_field_errors %}
        <ul class="text-red-600 text-sm">
            {% for error in form.non_field_errors %}
                <li class="text-center">{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <div class="grid grid-cols-2 gap-x-6 gap-y-8 max-md:grid-cols-1">
        {% for field in form %}
            <div class="flex flex-col gap-1 justify-end">
                {% if field.errors %}
                    {% for error in field.errors %}
                        <span class="text-red-600 text-sm">{{ error }}</span>
                    {% endfor %}
                {% endif %}
                {{ field }}
            </div>
        {% endfor %}
    </div>
{% endblock inputs %}
{% block btn_auth %}
    <button type="submit" class="mx-auto btn-primary w-80 max-md:w-[70vw] max-md:ml-0">Registrarse</button>
{% endblock btn_auth %}
{% block text_alt %}
    ¿ya tienes una cuenta? <a href="{% url "custom_auth:login" %}" class="text-blue-800 font-semibold tracking-wider transition-colors  hover:text-blue-900">Inicia sesión</a>
{% endblock text_alt %}

apps/custom_auth/templates/custom_auth/signup_done.html
{% extends "base/base_auth.html" %}
{% load static %}

{% block pag_descrip %} Signup success {% endblock pag_descrip %}
{% block title_pag %} Signup Success ✅ | BlogGate 💻 {% endblock title_pag %}
{% block favicon %}
    https://www.pngall.com/wp-content/uploads/2016/07/Success-PNG-Image.png
{% endblock favicon %}

{% block content %}
    <body class="min-h-screen flex justify-center items-center" style="
    background-image: linear-gradient(to right, #0000008c 0%, #0000008c 100%), url('https://img.freepik.com/foto-gratis/mano-humana-escribiendo-teclado-computadora-noche-generada-ai_188544-31050.jpg');
    background-repeat: no-repeat;
    background-size: cover;
    ">
        <section class="bg-white rounded-lg w-115 max-md:w-3/4_w h-auto px-5 py-6 flexbox1 gap-5">
            <h2 class="font-bold tracking-widest font-ubuntu text-xl">Registro exitoso!</h2>
            <p>Ya puedes iniciar sesión</p>
            <a class="btn-primary" href="{% url "custom_auth:login" %}">Login</a>
        </section>
    </body>
{% endblock content %} 